version: 2

workflows:
  version: 2
  test:
    jobs:
      - python_3.6
      - python_3.7
      - python_3.8
      - python_3.9
      - python_3.10

template: &template
  docker:
    - image: ubuntu:bionic
  steps:
    - checkout
    - run:
        name: Set up git + miniconda
        command: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y wget git-all
          cd $HOME
          wget "https://repo.anaconda.com/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh" -O miniconda.sh
          printf '%s' "8a324adcc9eaf1c09e22a992bb6234d91a94146840ee6b11c114ecadafc68121  miniconda.sh" | sha256sum -c
          bash miniconda.sh -b -p $HOME/miniconda
    - run:
        name: Set up environment, dependencies and run tests
        command: |
          export PATH="$HOME/miniconda/bin:$PATH"
          conda create -n torchfsdd python=$PYTHON_VERSION -y
          source activate torchfsdd
          pip install ".[dev]"
          pytest lib/test --disable-pytest-warnings

jobs:
  python_3.6:
    <<: *template
    environment:
      PYTHON_VERSION: "3.6"
  python_3.7:
    <<: *template
    environment:
      PYTHON_VERSION: "3.7"
  python_3.8:
    <<: *template
    environment:
      PYTHON_VERSION: "3.8"
  python_3.9:
    <<: *template
    environment:
      PYTHON_VERSION: "3.9"
  python_3.10:
    <<: *template
    environment:
      PYTHON_VERSION: "3.10"
